### ISSUE TITLE
Documentation: Back to Back Tutorial

### ISSUE THREAD

**Issue by ChristophHannappel** [sorengranfeldt/sqlma#10]
Hi,

is there a complete back to back tutorial on how to use the generic SQL Manamgent Agent?
I'm missing the configuration for the synchronisation and Export.
Basically i'm looking for a reference implementation guide.
I'm currently trying to update and create new rows and even with the help of two developers we are failing :)

**Comment by sorengranfeldt** [comment]
There is no tutorial on the Sync it self as knowledge of FIM/MIM Synchronization Service is expected. 
However, if you're missing any information on the SQL MA itself, let me no what information you seem to be missing from the Wiki. I, myself, have this MA running at several customers with success.

**Comment by ChristophHannappel** [comment]
Thanks. I think we're doing something wrong with the stored procedure syntax.
![export-config](https://user-images.githubusercontent.com/37103421/79866677-70b2d280-83dd-11ea-98c6-786dc9a81915.png)
On the sql profiler the sp is executed with null values.
![profiler](https://user-images.githubusercontent.com/37103421/79866741-8a541a00-83dd-11ea-9571-189f7cbc88ab.png)

**Comment by sorengranfeldt** [comment]
Okay. I get it. You're using the Microsoft Generic SQL MA and NOT this one. You'll have to consult the Microsoft documentation.
