### ISSUE TITLE
Errors not reported back to MIM

### ISSUE THREAD

**Issue by phwass** [sorengranfeldt/sqlma#16]
Hi Soren
Was setting this up and noticed that on export it returns success, no matter the outcome of the sql transaction as there is no throw in the catch blocks.  As a quick fix, I added

` throw new Microsoft.MetadirectoryServices.EntryExportException(ex.Message);`

to each export SQL function and it now returns errors if the update SQL fails. The actual error is in the eventlog (MIM just gets the 'unexpected-error') but that's enough for my purposes.

As a side note, I also added trace.flush to the finally blocks to force it to write the tracelog when its finished otherwise I kept losing information at the end of the stream (I'm impatient about logs during debugging :) ).

**Comment by sorengranfeldt** [comment]
I'll look into providing better error message in a future version
