### ISSUE TITLE
Build new Github release

### ISSUE THREAD

**Issue by mvaneijken** [sorengranfeldt/sqlma#17]
The last release of the sqlma does not reflect the current version. When possible, could you please create a new release and place that on the Github releases?

**Comment by sorengranfeldt** [comment]
I'll have a look. I have a refresh version coming soon, so maybe that'll be next release soon.

**Comment by sorengranfeldt** [comment]
New release coming soon

**Comment by sorengranfeldt** [comment]
New release out
