### ISSUE TITLE
Error on retrieving groupmemberships for principal running import

### ISSUE THREAD

**Issue by mvaneijken** [sorengranfeldt/sqlma#20]
Same error as discussed for the PSMA: https://github.com/sorengranfeldt/psma/issues/18

The error that occurs when is was not possible to retrieve all group memberships for the principal that runs the import: 
`Some or all identity references could not be translated.`

**Comment by sorengranfeldt** [comment]
Thank. Looks fine. I just need to find time to do the next release. I'm swamped with work right now, but will include in next release...

**Comment by sorengranfeldt** [comment]
Merged and included in release [1.0.2022.1054](https://github.com/sorengranfeldt/sqlma/releases/tag/1.0.2022.1054)
