### ISSUE TITLE
Anchors that contain special characters like "&" cannot be found

### ISSUE THREAD

**Issue by mvaneijken** [sorengranfeldt/sqlma#25]
Anchors that contain special characters like "&" cannot be found by the management agent. For instance:

Query `select * from [table] where anchor = 'Group-Example-Test OO - TEST OO & TEST-W'` does not return a row that exists and when including the "N" string prefix it does return a row: `select * from [table] where anchor = N'Group-Example-Test OO - TEST OO & TEST-W'`

For more information see: https://learn.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql?view=sql-server-ver16#remarks

**Comment by sorengranfeldt** [comment]
PR merged
