### ISSUE TITLE
Schema refresh fails with a multivalue table

### ISSUE THREAD

**Issue by mvaneijken** [sorengranfeldt/sqlma#5]
Schema refresh fails with a multi value table with the following schema's:

Singlevalue table:
```
CREATE TABLE [dbo].[SingleValueTable](
	[_id] [nvarchar](255) NOT NULL,
	[_objectclass] [nvarchar](50) NOT NULL,
	[_watermark] [datetime] NULL,
	[_isdeleted] [bit] NULL,
	[displayName] [nvarchar](255) NULL,
	[accountName] [nvarchar](255) NULL,
	[employeeID] [nvarchar](255) NULL,
	[dn] [nvarchar](255) NULL
) ON [PRIMARY]
```
Multivalue table:
```
CREATE TABLE [dbo].[MultiValueTable](
	[_refid] [nvarchar](255) NOT NULL,
	[_watermark] [datetime] NULL,
	[_isdeleted] [bit] NULL,
	[member] [nvarchar](255) NULL
) ON [PRIMARY]
```

The following error is recorded in the eventviewer:
    getschema, An item with the same key has already been added.

It seems that the _watermark column is not recognized correctly. 

The following configuration is used:

Item | Value 
------------ | ------------ 
Tablename | SingleValueTable
Tablename (multivalue) | MultiValueTable
Object class | Column
Object class (name or column) | _objectclass
Anchor column name | _id
DN column name | _id
IsDeleted column name | _isdeleted
Multivalue anchor reference column | _refid
Delta column type | DateTime
Delta column name | _watermark

The following schema configuration is used:

```
<configuration>
	<objectclasses>
		<objectclass name='person'>
			<excludes>
				<attribute name='member' />
			</excludes>
		</objectclass>
		<objectclass name='group'>
			<overrides>
                              <attribute name='member' schematype='reference' />
			</overrides>
		</objectclass>
	</objectclasses>
</configuration>
```

**Comment by sorengranfeldt** [comment]
Could you please add output from DebugView for this schema refresh? See troubleshooting for further

**Comment by mvaneijken** [comment]
Hereby the debug view results:

00000002	14.17473316	[24292] SQL.MA Information: 0 : enter initialize 	
00000003	14.18698406	[24292] SQL.MA Information: 0 :     sqlma-version 1.0.2017.1203 	
00000004	14.18706703	[24292] SQL.MA Information: 0 :     reading-registry-settings 	
00000005	14.18720436	[24292] SQL.MA Information: 0 :     adding-eventlog-listener-for name: Application, source: SQL Management Agent 	
00000006	14.20521259	[24292] SQL.MA Information: 0 : exit initialize 	
00000007	14.83295727	[24292] SQL.MA Information: 0 : enter initialize 	
00000008	14.84033585	[24292] SQL.MA Information: 0 :     sqlma-version 1.0.2017.1203 	
00000009	14.84041786	[24292] SQL.MA Information: 0 :     reading-registry-settings 	
00000010	14.84048843	[24292] SQL.MA Information: 0 :     adding-eventlog-listener-for name: Application, source: SQL Management Agent 	
00000011	14.85362244	[24292] SQL.MA Information: 0 : exit initialize 	
00000012	15.42596340	[24292] SQL.MA Information: 0 : enter initialize 	
00000013	15.43518543	[24292] SQL.MA Information: 0 :     sqlma-version 1.0.2017.1203 	
00000014	15.43524933	[24292] SQL.MA Information: 0 :     reading-registry-settings 	
00000015	15.43533421	[24292] SQL.MA Information: 0 :     adding-eventlog-listener-for name: Application, source: SQL Management Agent 	
00000016	15.44839191	[24292] SQL.MA Information: 0 : exit initialize 	
00000017	15.46107960	[24292] SQL.MA Information: 0 : enter getconfigparameters 	
00000018	15.46283245	[24292] SQL.MA Information: 0 : exit getconfigparameters 	
00000019	15.99334717	[24292] SQL.MA Information: 0 : enter initialize 	
00000020	16.00316048	[24292] SQL.MA Information: 0 :     sqlma-version 1.0.2017.1203 	
00000021	16.00323486	[24292] SQL.MA Information: 0 :     reading-registry-settings 	
00000022	16.00330925	[24292] SQL.MA Information: 0 :     adding-eventlog-listener-for name: Application, source: SQL Management Agent 	
00000023	16.01735115	[24292] SQL.MA Information: 0 : exit initialize 	
00000024	16.02722168	[24292] SQL.MA Information: 0 : enter getconfigparameters 	
00000025	16.02853012	[24292] SQL.MA Information: 0 : exit getconfigparameters 	
00000044	185.94000244	[24292] SQL.MA Information: 0 :   enter dispose-sql 	
00000045	185.94006348	[24292] SQL.MA Information: 0 :   exit dispose-sql 	
00000046	185.94044495	[24292] SQL.MA Information: 0 :   enter dispose-ma 	
00000047	185.94049072	[24292] SQL.MA Information: 0 :   exit dispose-ma 	
00000048	185.96781921	[24292] SQL.MA Information: 0 : enter dispose-sql 	
00000049	185.96788025	[24292] SQL.MA Information: 0 : exit dispose-sql 	
00000050	185.96813965	[24292] SQL.MA Information: 0 : enter dispose-ma 	
00000051	185.96818542	[24292] SQL.MA Information: 0 : exit dispose-ma 	
00000052	185.99630737	[24292] SQL.MA Information: 0 : enter dispose-sql 	
00000053	185.99636841	[24292] SQL.MA Information: 0 : exit dispose-sql 	
00000054	185.99664307	[24292] SQL.MA Information: 0 : enter dispose-ma 	
00000055	185.99670410	[24292] SQL.MA Information: 0 : exit dispose-ma 	
00000056	186.02171326	[24292] SQL.MA Information: 0 : enter dispose-sql 	
00000057	186.02177429	[24292] SQL.MA Information: 0 : exit dispose-sql 	
00000058	186.02210999	[24292] SQL.MA Information: 0 : enter dispose-ma 	
00000059	186.02218628	[24292] SQL.MA Information: 0 : exit dispose-ma 	
00000075	281.93795776	[24292] SQL.MA Information: 0 : enter initialize 	
00000076	281.94744873	[24292] SQL.MA Information: 0 :     sqlma-version 1.0.2017.1203 	
00000077	281.94754028	[24292] SQL.MA Information: 0 :     reading-registry-settings 	
00000078	281.94766235	[24292] SQL.MA Information: 0 :     adding-eventlog-listener-for name: Application, source: SQL Management Agent 	
00000079	281.96258545	[24292] SQL.MA Information: 0 : exit initialize 	
00000080	281.96994019	[24292] SQL.MA Information: 0 : enter validateconfigparameters 	
00000081	281.97021484	[24292] SQL.MA Information: 0 : exit validateconfigparameters 	
00000082	282.36120605	[24292] SQL.MA Information: 0 : enter initialize 	
00000083	282.37088013	[24292] SQL.MA Information: 0 :     sqlma-version 1.0.2017.1203 	
00000084	282.37094116	[24292] SQL.MA Information: 0 :     reading-registry-settings 	
00000085	282.37103271	[24292] SQL.MA Information: 0 :     adding-eventlog-listener-for name: Application, source: SQL Management Agent 	
00000086	282.38674927	[24292] SQL.MA Information: 0 : exit initialize 	
00000087	282.39654541	[24292] SQL.MA Information: 0 : enter getconfigparameters 	
00000088	282.39721680	[24292] SQL.MA Information: 0 : exit getconfigparameters 	
00000089	282.78076172	[24292] SQL.MA Information: 0 : enter initialize 	
00000090	282.79034424	[24292] SQL.MA Information: 0 :     sqlma-version 1.0.2017.1203 	
00000091	282.79040527	[24292] SQL.MA Information: 0 :     reading-registry-settings 	
00000092	282.79046631	[24292] SQL.MA Information: 0 :     adding-eventlog-listener-for name: Application, source: SQL Management Agent 	
00000093	282.80487061	[24292] SQL.MA Information: 0 : exit initialize 	
00000094	282.81533813	[24292] SQL.MA Information: 0 : enter getconfigparameters 	
00000095	282.81539917	[24292] SQL.MA Information: 0 : exit getconfigparameters 	
00000096	283.42068481	[24292] SQL.MA Information: 0 : enter initialize 	
00000097	283.42779541	[24292] SQL.MA Information: 0 :     sqlma-version 1.0.2017.1203 	
00000098	283.42785645	[24292] SQL.MA Information: 0 :     reading-registry-settings 	
00000099	283.42791748	[24292] SQL.MA Information: 0 :     adding-eventlog-listener-for name: Application, source: SQL Management Agent 	
00000100	283.44100952	[24292] SQL.MA Information: 0 : exit initialize 	
00000101	283.44375610	[24292] SQL.MA Information: 0 : enter getcapabilities 	
00000102	283.44433594	[24292] SQL.MA Information: 0 : exit getcapabilities 	
00000103	283.90505981	[24292] SQL.MA Information: 0 : enter initialize 	
00000104	283.91223145	[24292] SQL.MA Information: 0 :     sqlma-version 1.0.2017.1203 	
00000105	283.91238403	[24292] SQL.MA Information: 0 :     reading-registry-settings 	
00000106	283.91253662	[24292] SQL.MA Information: 0 :     adding-eventlog-listener-for name: Application, source: SQL Management Agent 	
00000107	283.92526245	[24292] SQL.MA Information: 0 : exit initialize 	
00000108	283.93444824	[24292] SQL.MA Information: 0 : enter initializeconfigparameters 	
00000109	283.93478394	[24292] SQL.MA Information: 0 :   Connection string: 'data source=DB;initial catalog=DB;Integrated Security=SSPI;multipleactiveresultsets=true' 	
00000110	283.93493652	[24292] SQL.MA Information: 0 :   Username: '' 	
00000111	283.93496704	[24292] SQL.MA Information: 0 :   Tablename: 'SingleValueTable' 	
00000112	283.93502808	[24292] SQL.MA Information: 0 :   Tablename (multivalue): 'MultiValueTable' 	
00000113	283.93508911	[24292] SQL.MA Information: 0 :   Object class: 'Column' 	
00000114	283.93511963	[24292] SQL.MA Information: 0 :   Object class (name or column): '_objectclass' 	
00000115	283.93518066	[24292] SQL.MA Information: 0 :   Anchor column name: '_id' 	
00000116	283.93527222	[24292] SQL.MA Information: 0 :   DN column name: '_id' 	
00000117	283.93536377	[24292] SQL.MA Information: 0 :   IsDeleted column name: '_isdeleted' 	
00000118	283.93542480	[24292] SQL.MA Information: 0 :   Multivalue anchor reference column: '_refid' 	
00000119	283.93545532	[24292] SQL.MA Information: 0 :   Delta column type: 'DateTime' 	
00000120	283.93551636	[24292] SQL.MA Information: 0 :   Delta column name: '_watermark' 	
00000121	283.93557739	[24292] SQL.MA Information: 0 :   Schema Configuration: '<configuration>	
00000122	283.93557739	[24292]  <objectclasses>	
00000123	283.93557739	[24292]   <objectclass name='person'>	
00000124	283.93557739	[24292]      <excludes>	
00000125	283.93557739	[24292]        <attribute name='member' />	
00000126	283.93557739	[24292]    </excludes>	
00000127	283.93557739	[24292]   </objectclass>	
00000128	283.93557739	[24292]   <objectclass name='group'>	
00000129	283.93557739	[24292]    <overrides>	
00000130	283.93557739	[24292]     <attribute name='member' schematype='reference' />	
00000131	283.93557739	[24292] 	
00000132	283.93557739	[24292]    </overrides>	
00000133	283.93557739	[24292] 	
00000134	283.93557739	[24292]   </objectclass>	
00000135	283.93557739	[24292]  </objectclasses>	
00000136	283.93557739	[24292] </configuration>	
00000137	283.93557739	[24292] 	
00000138	283.93557739	[24292] ' 	
00000139	284.40560913	[24292] SQL.MA Information: 0 : exit initializeconfigparameters 	
00000140	284.41024780	[24292] SQL.MA Information: 0 : enter getschema 	
00000141	284.42230225	[24292] SQL.MA Information: 0 :   enter openconnection 	
00000142	284.42236328	[24292] SQL.MA Information: 0 :     connection-string data source=DB;initial catalog=DB;Integrated Security=SSPI;multipleactiveresultsets=true 	
00000143	284.69998169	[24292] SQL.MA Information: 0 :     sql-server-version 14.00.3223 	
00000144	284.70007324	[24292] SQL.MA Information: 0 :   exit openconnection 	
00000145	284.70016479	[24292] SQL.MA Information: 0 :   objectclass-type Column 	
00000146	284.70181274	[24292] SQL.MA Information: 0 :   enter getobjectclasses 	
00000147	284.70184326	[24292] SQL.MA Information: 0 :     run-query 'select distinct _objectclass from [SingleValueTable]' 	
00000148	284.76217651	[24292] SQL.MA Information: 0 :     name: _objectclass, value: person 	
00000149	284.76296997	[24292] SQL.MA Information: 0 :     name: _objectclass, value: group 	
00000150	284.76953125	[24292] SQL.MA Information: 0 :   exit getobjectclasses 	
00000151	284.77056885	[24292] SQL.MA Information: 0 :   enter getschema 	
00000152	284.77059937	[24292] SQL.MA Information: 0 :     run-query 'select top 1 * from [SingleValueTable]' 	
00000153	284.77545166	[24292] SQL.MA Information: 0 :     name: _id, sql-type: nvarchar, selected-schematype: String 	
00000154	284.77560425	[24292] SQL.MA Information: 0 :     name: _objectclass, sql-type: nvarchar, selected-schematype: String 	
00000155	284.77566528	[24292] SQL.MA Information: 0 :     name: _watermark, sql-type: datetime, selected-schematype: String 	
00000156	284.77572632	[24292] SQL.MA Information: 0 :     name: _isdeleted, sql-type: bit, selected-schematype: Boolean 	
00000157	284.77578735	[24292] SQL.MA Information: 0 :     name: displayName, sql-type: nvarchar, selected-schematype: String 	
00000158	284.77584839	[24292] SQL.MA Information: 0 :     name: accountName, sql-type: nvarchar, selected-schematype: String 	
00000159	284.77587891	[24292] SQL.MA Information: 0 :     name: employeeID, sql-type: nvarchar, selected-schematype: String 	
00000160	284.77593994	[24292] SQL.MA Information: 0 :     name: dn, sql-type: nvarchar, selected-schematype: String 	
00000161	284.77664185	[24292] SQL.MA Information: 0 :   exit getschema 	
00000162	284.77691650	[24292] SQL.MA Information: 0 :   enter getschema 	
00000163	284.77694702	[24292] SQL.MA Information: 0 :     run-query 'select top 1 * from [MultiValueTable]' 	
00000164	284.77740479	[24292] SQL.MA Information: 0 :     name: _refid, sql-type: nvarchar, selected-schematype: String 	
00000165	284.77743530	[24292] SQL.MA Information: 0 :     name: _watermark, sql-type: datetime, selected-schematype: String 	
00000166	284.77749634	[24292] SQL.MA Information: 0 :     name: _isdeleted, sql-type: bit, selected-schematype: Boolean 	
00000167	284.77755737	[24292] SQL.MA Information: 0 :     name: member, sql-type: nvarchar, selected-schematype: String 	
00000168	284.77761841	[24292] SQL.MA Information: 0 :   exit getschema 	
00000169	284.77774048	[24292] SQL.MA Information: 0 :   start-object-class person 	
00000170	284.77917480	[24292] SQL.MA Information: 0 :     found-schemaxml-information-for person 	
00000171	284.78039551	[24292] SQL.MA Information: 0 :     adding-anchor name: _id, type: String [ImportExport] 	
00000172	284.78106689	[24292] SQL.MA Information: 0 :     skipping-reserved-column _objectclass 	
00000173	284.78109741	[24292] SQL.MA Information: 0 :     add-singlevalue name: _watermark, type: String [ImportExport] 	
00000174	284.78131104	[24292] SQL.MA Information: 0 :     skipping-reserved-column _isdeleted 	
00000175	284.78137207	[24292] SQL.MA Information: 0 :     add-singlevalue name: displayName, type: String [ImportExport] 	
00000176	284.78140259	[24292] SQL.MA Information: 0 :     add-singlevalue name: accountName, type: String [ImportExport] 	
00000177	284.78146362	[24292] SQL.MA Information: 0 :     add-singlevalue name: employeeID, type: String [ImportExport] 	
00000178	284.78155518	[24292] SQL.MA Information: 0 :     add-singlevalue name: dn, type: String [ImportExport] 	
00000179	284.78170776	[24292] SQL.MA Information: 0 :     skipping-reserved-column _refid 	
00000180	284.78176880	[24292] SQL.MA Information: 0 :     add-multivalue name: _watermark, type: String [ImportExport] 	
00000181	284.78247070	[24292] SQL.MA Information: 0 :     enter dispose-sql 	
00000182	284.78250122	[24292] SQL.MA Information: 0 :       disposing-managed-objects 	
00000183	284.78283691	[24292] SQL.MA Information: 0 :       enter closeconnection 	
00000184	284.78292847	[24292] SQL.MA Information: 0 :         connection-state Open 	
00000185	284.79104614	[24292] SQL.MA Information: 0 :         connection-closed 	
00000186	284.79107666	[24292] SQL.MA Information: 0 :       exit closeconnection 	
00000187	284.79113770	[24292] SQL.MA Information: 0 :     exit dispose-sql 	
00000188	284.79141235	[24292] SQL.MA Error: -2147024809 :     getschema, An item with the same key has already been added. 	
00000189	284.79785156	[24292] SQL.MA Information: 0 :   exit getschema

**Comment by sorengranfeldt** [comment]
From the log it looks like you haven’t specified correct name in the configuration for the watermark column since it is adding it as a normal column. And that’s why you get the duplicate. 

Check column names on the Properties of the MA

**Comment by mvaneijken** [comment]
Yes, when removing the _watermark column temporary from the multivalue talble it appears as a selectable property. That's not ok, it's not picking it up als a delta field. The thing is, when selecting RowVersion with the same columns name there is no problem. Although the import won't work because I eat to use an date time datatype for this.

**Comment by sorengranfeldt** [comment]
Did you find a solution for this - or is it still a problem?

**Comment by mvaneijken** [comment]
No, there seems to be something wrong in recognizing the watermark column when it's of the datetime datatype.

**Comment by sorengranfeldt** [comment]
Hmmm. I need to have a look at it for a customer, so I may be able to fix any issue within a short while. I see if I can reproduce the problem. Also, I'd like to add a feature to handle the datetime formatting issue.

**Comment by sorengranfeldt** [comment]
Could you try out latest release (sql.ma.1.0.2019.1113) and see if that version fixes your problem? I have it working with your tables now in my environment ?

**Comment by mvaneijken** [comment]
Thanks! I'll do that, and keep you updated on this!

**Comment by sorengranfeldt** [comment]
Did this release fix your issue ? Please close issue if so

**Comment by mvaneijken** [comment]
Sorry never responded, but yea, it was fixed!
